export const languages = [
  { value: "English", label: "English" },
  { value: "Spanish", label: "Spanish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "French", label: "French" },
  { value: "German", label: "German" },
  { value: "Italian", label: "Italian" },
  { value: "Dutch", label: "Dutch" },
  { value: "Russian", label: "Russian" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Polish", label: "Polish" },
  { value: "Czech", label: "Czech" },
  { value: "Slovak", label: "Slovak" },
  { value: "Slovenian", label: "Slovenian" },
  { value: "Croatian", label: "Croatian" },
  { value: "Bosnian", label: "Bosnian" },
  { value: "Serbian", label: "Serbian" },
  { value: "Montenegrin", label: "Montenegrin" },
  { value: "Macedonian", label: "Macedonian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Romanian", label: "Romanian" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Greek", label: "Greek" },
  { value: "Turkish", label: "Turkish" },
  { value: "Albanian", label: "Albanian" },
  { value: "Georgian", label: "Georgian" },
  { value: "Armenian", label: "Armenian" },

  { value: "Arabic", label: "Arabic" },
  { value: "Hebrew", label: "Hebrew" },
  { value: "Persian", label: "Persian (Farsi)" },
  { value: "Kurdish", label: "Kurdish" },

  { value: "Hindi", label: "Hindi" },
  { value: "Urdu", label: "Urdu" },
  { value: "Bengali", label: "Bengali" },
  { value: "Punjabi", label: "Punjabi" },
  { value: "Gujarati", label: "Gujarati" },
  { value: "Marathi", label: "Marathi" },
  { value: "Tamil", label: "Tamil" },
  { value: "Telugu", label: "Telugu" },
  { value: "Kannada", label: "Kannada" },
  { value: "Malayalam", label: "Malayalam" },
  { value: "Sinhala", label: "Sinhala" },
  { value: "Nepali", label: "Nepali" },

  { value: "Chinese", label: "Chinese (Mandarin)" },
  { value: "Cantonese", label: "Chinese (Cantonese)" },
  { value: "Japanese", label: "Japanese" },
  { value: "Korean", label: "Korean" },
  { value: "Thai", label: "Thai" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Tagalog", label: "Tagalog (Filipino)" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Malay", label: "Malay" },

  { value: "Swahili", label: "Swahili" },
  { value: "Yoruba", label: "Yoruba" },
  { value: "Zulu", label: "Zulu" },
  { value: "Amharic", label: "Amharic" },
  { value: "Hausa", label: "Hausa" },
  { value: "Somali", label: "Somali" },

  { value: "Finnish", label: "Finnish" },
  { value: "Swedish", label: "Swedish" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Danish", label: "Danish" },
  { value: "Icelandic", label: "Icelandic" },

  { value: "Irish", label: "Irish Gaelic" },
  { value: "Welsh", label: "Welsh" },
  { value: "Scottish Gaelic", label: "Scottish Gaelic" },

  { value: "Latin", label: "Latin" },
];
